import {useEffect,useState} from 'react';
import {CoinIcon,price} from './MarketTools';
type Row={symbol:string;price:number;turnover24h:number;change24h:number;checked_ms:number;quality:number;phase:string;side:string;setup:string;blockers:string[];entry:number|null;stop:number|null;tp1:number|null;tp2:number|null;first_seen_ms:number};
type Scan={status:string;completed_ms:number;scanning_symbol:string;scanned:number;rows:Row[];error:string|null};
type Agent={jev?:{status:string;last_review:string;last_success_ms:number;error:string|null};calibration?:{state:string;samples:number;required:number;reason:string};scanner?:{status:string;error:string|null}};
export function MarketSidebar({onSelect,busy}:{onSelect:(symbol:string)=>void;busy:boolean}){
 const [scan,setScan]=useState<Scan|null>(null);const [agent,setAgent]=useState<Agent>({});const [error,setError]=useState('');const [tab,setTab]=useState<'ranked'|'volume'>('ranked');const [now,setNow]=useState(Date.now());
 useEffect(()=>{let live=true;let running=false;const controller=new AbortController();async function poll(){if(running)return;running=true;try{const [s,h]=await Promise.all([fetch('/api/scanner',{signal:controller.signal}),fetch('/api/health',{signal:controller.signal})]);if(!s.ok||!h.ok)throw Error('Agent status unavailable');const [sv,hv]=await Promise.all([s.json(),h.json()]);if(live){setScan(sv);setAgent(hv.agent??{});setError('');setNow(Date.now());}}catch(e){if(live)setError(String(e));}finally{running=false;}}
 void poll();const timer=setInterval(poll,4000);return()=>{live=false;controller.abort();clearInterval(timer);};},[]);
 const rows=[...(scan?.rows??[])].sort((a,b)=>tab==='volume'?b.turnover24h-a.turnover24h:(Number(b.phase.startsWith('candidate'))-Number(a.phase.startsWith('candidate'))||b.quality-a.quality));
 return <aside className="market-sidebar panel"><h2>Market radar</h2><p className="muted">Top 20 USDT perpetuals by 24h quote volume. 5m setups with 15m confirmation.</p><div className="radar-tabs"><button className={tab==='ranked'?'active':''} onClick={()=>setTab('ranked')}>Ranked setups</button><button className={tab==='volume'?'active':''} onClick={()=>setTab('volume')}>Volume leaders</button></div>
 <div className="agent-pulse"><i style={{background:error||scan?.status==='unavailable'?'#e4a75f':'#50d9a8'}}/>{scan?.status??'starting'} · {scan?.scanned??0}/20<br/>{scan?.scanning_symbol&&`Checking ${scan.scanning_symbol}`}</div>
 <p className="radar-note">Ranking is technical quality, not measured accuracy. A candidate needs live order-flow confirmation before paper entry.</p>
 {(error||scan?.error)&&<p className="market-error">{error||scan?.error}</p>}
 <details className="agent-detail"><summary>Agent activity</summary><p><b>Jev: {agent.jev?.status??'starting'}</b></p><p>Last response: {agent.jev?.last_success_ms?new Date(agent.jev.last_success_ms).toLocaleTimeString():'none yet'}</p><p>{agent.jev?.last_review||'Waiting for a fresh market review.'}</p>{agent.jev?.error&&<p className="negative">{agent.jev.error}</p>}<p><b>Calibration: {agent.calibration?.state??'starting'}</b><br/>{agent.calibration?.samples??0}/{agent.calibration?.required??500} completed outcomes</p><p>{agent.calibration?.reason}</p><p>Paper positions are monitored independently of the chart. Scanner candidates never submit orders.</p></details>
 <div className="radar-list">{rows.map((r,i)=>{const age=r.checked_ms?Math.max(0,Math.floor((now-r.checked_ms)/1000)):null;const stale=age===null||age>180;return <button key={r.symbol} disabled={busy} className="radar-row" onClick={()=>onSelect(r.symbol)}><div className="radar-title"><span>{i+1}.</span><CoinIcon base={r.symbol.replace(/USDT$/,'')}/><strong>{r.symbol}</strong><b className={r.side==='long'?'positive':r.side==='short'?'negative':''}>{r.side.toUpperCase()}</b></div><div className="radar-values"><span>{price(r.price)}</span><span>${(r.turnover24h/1e6).toFixed(1)}M / 24h</span></div><div className="radar-phase">{stale?'Stale / warming':r.phase} · {(r.quality*100).toFixed(0)}% quality</div><small>{r.setup.replaceAll('_',' ')} {age!==null?`· ${age}s ago`:''}</small>{r.entry!=null&&<small>Watch {price(r.entry)} · SL {price(r.stop!)} · TP {price(r.tp2!)}</small>}<small className="muted">{r.blockers.slice(0,2).join('; ')}</small></button>;})}</div>
</aside>;
}
