use crate::{runtime::{self, RuntimeMarketConfig, RuntimeMarketUpdate},state::AppState};
use axum::{extract::{ws::{Message, WebSocket, WebSocketUpgrade},State},http::StatusCode,response::IntoResponse,routing::{get,post},Json,Router};
use serde_json::json;
use std::time::Duration;
use tokio::time;
use tower_http::cors::CorsLayer;

pub fn router(state: AppState) -> Router {Router::new().route("/api/health",get(health)).route("/api/paper",get(paper_view)).route("/api/paper/enter",post(paper_enter)).route("/api/paper/close",post(paper_close)).route("/api/paper/reset",post(paper_reset)).route("/api/scanner",get(||async{Json(crate::scanner::snapshot())})).route("/api/instruments",get(instruments)).route("/api/state",get(snapshot)).route("/api/market",get(market_config).post(update_market)).route("/ws",get(ws_upgrade)).layer(axum::extract::DefaultBodyLimit::max(16*1024)).layer(axum::middleware::from_fn(local_origin)).layer(CorsLayer::new().allow_origin(["http://127.0.0.1:5173".parse::<axum::http::HeaderValue>().unwrap(),"http://localhost:5173".parse().unwrap()]).allow_methods([axum::http::Method::GET,axum::http::Method::POST]).allow_headers([axum::http::header::CONTENT_TYPE])).with_state(state)}
async fn instruments(State(state):State<AppState>)->Json<crate::catalog::Catalog>{Json(crate::catalog::get(state.config.bybit_testnet).await)}
async fn local_origin(request:axum::extract::Request,next:axum::middleware::Next)->axum::response::Response{if let Some(origin)=request.headers().get(axum::http::header::ORIGIN){if !matches!(origin.to_str(),Ok("http://127.0.0.1:5173"|"http://localhost:5173"|"http://127.0.0.1:8787"|"http://localhost:8787")){return StatusCode::FORBIDDEN.into_response();}}next.run(request).await}
async fn health(State(state):State<AppState>)->Json<serde_json::Value>{let snapshot=state.snapshot();let jev=crate::jev::status();let scanner=crate::scanner::snapshot();let calibration=crate::model::calibration_status();let model_status=if let Some(ref model)=state.inner.read().model{format!("deployed ({})",model.model.model_version)}else{format!("{} ({}/{})",calibration["state"].as_str().unwrap_or("unavailable"),calibration["samples"].as_u64().unwrap_or(0),calibration["required"].as_u64().unwrap_or(500))};Json(json!({"ok":snapshot.connected&&!snapshot.feed_stale&&snapshot.features.is_some(),"connected":snapshot.connected,"services":{"market_feed":if snapshot.connected&&!snapshot.feed_stale{"live"}else{"unavailable"},"signal_engine":if snapshot.analyses.len()==4&&!snapshot.feed_stale{"evaluating"}else{"warming / halted"},"history":if snapshot.analyses.len()==4{"ready"}else{"loading"},"jev":jev.status,"scanner":scanner.status,"paper_account":state.paper.lock().view().monitoring,"execution":"paper only","calibrated_model":model_status},"agent":{"jev":jev,"calibration":calibration,"scanner":{"status":scanner.status,"scanned":scanner.scanned,"total":scanner.rows.len(),"current_symbol":scanner.scanning_symbol,"completed_ms":scanner.completed_ms,"error":scanner.error}},"symbol":snapshot.symbol,"updated_at_ms":snapshot.updated_at_ms}))}
async fn snapshot(State(state):State<AppState>)->Json<crate::types::EngineSnapshot>{Json(state.snapshot())}
async fn market_config()->Json<RuntimeMarketConfig>{Json(runtime::current())}
async fn update_market(State(state):State<AppState>,Json(request):Json<RuntimeMarketUpdate>)->Result<Json<RuntimeMarketConfig>,(StatusCode,Json<serde_json::Value>)>{if let Some(symbol)=&request.symbol{let catalog=crate::catalog::get(state.config.bybit_testnet).await;if catalog.instruments.is_empty(){return Err((StatusCode::SERVICE_UNAVAILABLE,Json(json!({"error":"Cannot validate symbol: exchange catalog unavailable"}))));}if !catalog.instruments.iter().any(|i|i.symbol==symbol.trim().to_ascii_uppercase()){return Err((StatusCode::BAD_REQUEST,Json(json!({"error":"Symbol is not an active Bybit linear perpetual. Select a ticker from search."}))));}}let previous=runtime::current();let next=runtime::update(request).map_err(|error|(StatusCode::BAD_REQUEST,Json(json!({"error":error.to_string()}))))?;if next.symbol!=previous.symbol{let now=crate::state::now_ms();let invalidated={let mut inner=state.inner.write();let invalidated=inner.invalidate_market_signals(now,&format!("Market changed from {} to {}.",previous.symbol,next.symbol));inner.reset_market();invalidated};for signal in invalidated{state.publish(crate::types::EngineEvent{ts_ms:now,event_type:"invalidated".into(),alert:Some(crate::types::AlertKind::Invalidated),message:format!("{} {}m {:?} setup invalidated because the selected market changed; old signal {} remains in history",signal.symbol,signal.timeframe,signal.side,signal.id),signal:Some(signal)});}}else if next.timeframe!=previous.timeframe{state.inner.write().reset_signal_context();}state.publish(crate::types::EngineEvent{ts_ms:crate::state::now_ms(),event_type:"market_update_requested".into(),alert:None,message:format!("Requested {} on {}m (generation {}).",next.symbol,next.timeframe,next.generation),signal:None});Ok(Json(next))}
async fn ws_upgrade(ws:WebSocketUpgrade,State(state):State<AppState>)->impl IntoResponse{ws.on_upgrade(move|socket|ws_loop(socket,state))}
async fn ws_loop(mut socket:WebSocket,state:AppState){let mut events=state.events.subscribe();let initial=json!({"kind":"snapshot","data":state.snapshot()}).to_string();if socket.send(Message::Text(initial.into())).await.is_err(){return;}let mut snapshots=time::interval(Duration::from_millis(750));loop{tokio::select!{_=snapshots.tick()=>{let payload=json!({"kind":"snapshot","data":state.snapshot()}).to_string();if socket.send(Message::Text(payload.into())).await.is_err(){break;}},event=events.recv()=>{let Ok(event)=event else{continue;};let payload=json!({"kind":"event","data":event}).to_string();if socket.send(Message::Text(payload.into())).await.is_err(){break;}}}}}
#[derive(serde::Deserialize)]struct PaperEntry{signal_id:String,notional:f64}
#[derive(serde::Deserialize)]struct PaperClose{position_id:String}
#[derive(serde::Deserialize)]struct PaperReset{confirmation:String,revision:u64}
type ApiError=(StatusCode,Json<serde_json::Value>);
fn paper_error(e:impl ToString)->ApiError{(StatusCode::BAD_REQUEST,Json(json!({"error":e.to_string()})))}
fn paper_risk_halt(paper:&crate::paper::Paper)->anyhow::Result<Option<crate::risk::RiskHaltReason>>{let mut closed=paper.account.positions.iter().filter(|p|p.closed_ms.is_some()).collect::<Vec<_>>();closed.sort_by_key(|p|p.closed_ms);let mut equity=paper.account.initial_balance;let mut history=Vec::with_capacity(closed.len());for p in closed{equity+=p.realized_pnl;history.push(equity);}crate::risk::evaluate_equity_history(paper.account.initial_balance,history,paper.view().equity,crate::risk::RiskLimits{max_daily_loss_fraction:0.05,max_drawdown_fraction:0.03})}
fn paper_exposure_admission(paper:&crate::paper::Paper,symbol:&str,notional:f64)->anyhow::Result<()>{let view=paper.view();let open=paper.account.positions.iter().filter(|p|p.remaining>0.0).map(|p|crate::risk::OpenExposure{symbol:&p.symbol,notional:p.entry*p.remaining});crate::risk::evaluate_new_exposure(view.equity,symbol,notional,open,crate::risk::ExposureLimits{max_total_fraction:0.50,max_symbol_fraction:0.25,max_open_positions:3})}
async fn paper_view(State(state):State<AppState>)->Json<crate::paper::View>{Json(state.paper.lock().view())}
async fn paper_enter(State(state):State<AppState>,Json(request):Json<PaperEntry>)->Result<Json<crate::paper::View>,ApiError>{let market=runtime::current();let inner=state.inner.read();if !inner.connected||inner.feed_stale||crate::state::now_ms().saturating_sub(inner.orderbook_event_ms)>state.config.stale_feed_ms{return Err(paper_error("Fresh selected-market feed required"));}let signal=inner.signals.values().find(|s|s.id==request.signal_id&&s.symbol==market.symbol).ok_or_else(||paper_error("Signal no longer available"))?;let bid=inner.bid.ok_or_else(||paper_error("No bid"))?;let ask=inner.ask.ok_or_else(||paper_error("No ask"))?;let mut paper=state.paper.lock();if let Some(reason)=paper_risk_halt(&paper).map_err(paper_error)?{return Err(paper_error(format!("Paper risk halt: {reason}; reset the paper session explicitly before new entries")));}paper_exposure_admission(&paper,&signal.symbol,request.notional).map_err(paper_error)?;paper.enter(signal,request.notional,bid,ask,crate::state::now_ms()).map_err(paper_error)?;Ok(Json(paper.view()))}
async fn paper_close(State(state):State<AppState>,Json(request):Json<PaperClose>)->Result<Json<crate::paper::View>,ApiError>{let symbol={let paper=state.paper.lock();paper.account.positions.iter().find(|p|p.id==request.position_id&&p.remaining>0.0).map(|p|p.symbol.clone()).ok_or_else(||paper_error("Open position not found"))?};let quotes=crate::paper::quotes(state.config.bybit_testnet).await.map_err(paper_error)?;let quote=quotes.get(&symbol).ok_or_else(||paper_error("No fresh price for this symbol"))?;let mut paper=state.paper.lock();paper.close(&request.position_id,quote.bid,quote.ask,quote.ts).map_err(paper_error)?;Ok(Json(paper.view()))}
async fn paper_reset(State(state):State<AppState>,Json(request):Json<PaperReset>)->Result<Json<crate::paper::View>,ApiError>{let mut paper=state.paper.lock();if request.confirmation!="RESET"||request.revision!=paper.account.revision{return Err(paper_error("Account changed or reset unconfirmed; refresh and retry"));}paper.reset().map_err(paper_error)?;Ok(Json(paper.view()))}
